# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.5
_src_path: gh:jupyterlab/extension-template
author_email: ''
author_name: Project Jupyter Contributors
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: frontend
labextension_name: '@jupyterlab-examples/react-auth-google'
mimetype: ''
mimetype_name: ''
project_short_description: A minimal JupyterLab extension using a React Widget.
python_name: jupyterlab_examples_react_auth_google
repository: https://github.com/jupyterlab/extension-examples
test: true
viewer_name: ''

