# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.4
_src_path: gh:jupyterlab/extension-template
author_email: ''
author_name: Project Jupyter Contributors
data_format: string
file_extension: ''
has_binder: false
has_settings: true
kind: frontend
labextension_name: '@jupyterlab-examples/launcher'
mimetype: ''
mimetype_name: ''
project_short_description: A minimal JupyterLab example using the launcher.
python_name: jupyterlab_examples_launcher
repository: https://github.com/jupyterlab/extension-examples
test: true
viewer_name: ''

