# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.6
_src_path: gh:jupyterlab/extension-template
author_email: ''
author_name: Project Jupyter Contributors
data_format: string
file_extension: ''
has_binder: false
has_settings: true
kind: frontend
labextension_name: '@jupyterlab-examples/kernel-messaging'
mimetype: ''
mimetype_name: ''
project_short_description: JupyterLab extension example for kernel messaging.
python_name: jupyterlab_examples_kernel_messaging
repository: https://github.com/jupyterlab/extension-examples
test: true
viewer_name: ''

