# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.6
_src_path: gh:jupyterlab/extension-template
author_email: ''
author_name: Project Jupyter Contributors
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: frontend
labextension_name: '@jupyterlab-examples/command-palette'
mimetype: ''
mimetype_name: ''
project_short_description: Minimal JupyterLab example adding a new command to the
    palette.
python_name: jupyterlab_examples_command_palette
repository: https://github.com/jupyterlab/extension-examples
test: true
viewer_name: ''

