# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.4
_src_path: gh:jupyterlab/extension-template
author_email: ''
author_name: Project Jupyter Contributors
data_format: string
file_extension: ''
has_binder: false
has_settings: true
kind: frontend
labextension_name: '@jupyterlab-examples/toolbar-button'
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension adding a button to the Notebook
    toolbar.
python_name: jupyterlab_examples_toolbar_button
repository: https://github.com/jupyterlab/extension-examples
test: true
viewer_name: ''

