# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: me@test.com
author_name: My Name
has_binder: false
has_settings: false
kind: frontend
labextension_name: leap_counter_extension
project_short_description: Adds a leap counter/button (1 of 3 related examples). This
    extension holds the UI/interface.
python_name: leap_counter_extension
repository: ''
test: true

